ShoppingCart/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from User.urls import user_urlpattern
from Shoppingapp.product_urls import product_urlpattern


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include(user_urlpattern)),    
    url(r'^product/', include(product_urlpattern)),    
    url(r'^$', 'Shoppingapp.views.home',name='home'),
    url(r'^home/', 'Shoppingapp.views.home',name='home'),
    url(r'^blog/', 'Shoppingapp.views.blog',name='blog'),
    url(r'^cart/', 'Shoppingapp.views.cart',name='cart'),
    url(r'^checkout/', 'Shoppingapp.views.checkout',name='checkout'),
    url(r'^contact/', 'Shoppingapp.views.contact',name='contact'),
    url(r'^product/', 'Shoppingapp.views.product',name='product'),
    url(r'^shop/', 'Shoppingapp.views.shop',name='shop'),
    url(r'^product-details/', 'Shoppingapp.views.product_detail',name='product_detail'),
    url(r'^blog-single/', 'Shoppingapp.views.blog_single',name='blog_single'),
    url(r'^page-not-found/', 'Shoppingapp.views.page_not_found',name='page_not_found'),
    url(r'^signin/', 'Shoppingapp.views.signin',name='signin'),
]

User/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from Shoppingapp import views
from ShoppingCart import settings
from django.conf.urls.static import static

user_urlpattern = [
    url(r'^signup/', 'User.views.signup',name='signup'),
    url(r'^signout/', 'User.views.sign_out',name='sign_out'),
    url(r'^signin/', 'User.views.signin',name='signin'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shoppingapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template import RequestContext
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.contrib.auth import login
#from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_control
from django.contrib import auth
from django.db import models
#from constants import AppUserConstants, ExceptionLabel
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.template import RequestContext
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
import datetime
# importing mysqldb and system packages

# Create your models here.
status = (
    ('1','1'),
    ('0','0'),
    
)

availability_status = (
    ('1','In Stock'),
    ('0','Out Of Stock'),
)


PRODUCT_IMAGES_PATH ='images/product_images/' 

class Customer(User):
    customer_id			=       models.AutoField(primary_key=True, editable=False)
    customer_first_name =       models.CharField(max_length=45,null=True,blank=True)
    customer_last_name  =       models.CharField(max_length=45,null=True,blank=True)
    customer_email      =       models.CharField(max_length=45,null=True,blank=True)
    customer_status		=       models.CharField(max_length=1,default="1",choices=status)
    created_date       	=       models.DateTimeField(null=True,blank=True,default=datetime.datetime.now())
    fb_token			=       models.CharField(max_length=100,null=True,blank=True)
    twitter_token		=       models.CharField(max_length=100,null=True,blank=True)
    google_token		=       models.CharField(max_length=100,null=True,blank=True)

    def __unicode__(self):
    	return unicode(self.customer_id)


class Category(models.Model):
    category_id         =       models.AutoField(primary_key=True, editable=False)
    category_name       =       models.CharField(max_length=45,null=True,blank=True)
    created_date        =       models.DateTimeField(null=True,blank=True,default=datetime.datetime.now())
    category_status     =       models.CharField(max_length=1,default="1",choices=status)

    def __unicode__(self):
        return unicode(self.category_id)


class Brand(models.Model):
    brand_id         =       models.AutoField(primary_key=True, editable=False)
    brand_name       =       models.CharField(max_length=45,null=True,blank=True)
    created_date     =       models.DateTimeField(null=True,blank=True,default=datetime.datetime.now())
    brand_status     =       models.CharField(max_length=1,default="1",choices=status)

    def __unicode__(self):
        return unicode(self.brand_id)

class Product(models.Model):
    product_id       =       models.AutoField(primary_key=True, editable=False)
    brand_id            =       models.ForeignKey(Brand,blank=True)
    created_date     =       models.DateTimeField(null=True,blank=True,default=datetime.datetime.now())
    product_status   =       models.CharField(max_length=1,default="1",choices=status)

    def __unicode__(self):
        return unicode(self.product_id)        

class ProductDetail(models.Model):
    product_detail_id     =       models.AutoField(primary_key=True, editable=False)
    product_id            =       models.ForeignKey(Product,blank=True)
    product_name          =       models.CharField(max_length=45,null=True,blank=True)
    product_price         =       models.IntegerField(null=True,blank=True)
    created_date          =       models.DateTimeField(null=True,blank=True,default=datetime.datetime.now())
    product_image         =       models.ImageField("Image",upload_to=PRODUCT_IMAGES_PATH,max_length=500, default=None)
    product_status        =       models.CharField(max_length=1,default="1",choices=status)
    product_availability  =       models.CharField(max_length=1,default="1",choices=availability_status)
    product_quantity      =       models.IntegerField(null=True,blank=True)

    def __unicode__(self):
        return unicode(self.product_detail_id)        


class ProductReviews(models.Model):
    product_review_id     =       models.AutoField(primary_key=True, editable=False)
    product_id            =       models.ForeignKey(Product,blank=True)
    user_name          =       models.CharField(max_length=45,null=True,blank=True)
    user_email          =       models.CharField(max_length=45,null=True,blank=True)
    user_review          =       models.CharField(max_length=45,null=True,blank=True)
    created_date          =       models.DateTimeField(null=True,blank=True,default=datetime.datetime.now())

    def __unicode__(self):
        return unicode(self.product_review_id)        

templates/blog.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}

	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Sportswear
										</a>
									</h4>
								</div>
								<div id="sportswear" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="">Nike </a></li>
											<li><a href="">Under Armour </a></li>
											<li><a href="">Adidas </a></li>
											<li><a href="">Puma</a></li>
											<li><a href="">ASICS </a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#mens">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Mens
										</a>
									</h4>
								</div>
								<div id="mens" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="">Fendi</a></li>
											<li><a href="">Guess</a></li>
											<li><a href="">Valentino</a></li>
											<li><a href="">Dior</a></li>
											<li><a href="">Versace</a></li>
											<li><a href="">Armani</a></li>
											<li><a href="">Prada</a></li>
											<li><a href="">Dolce and Gabbana</a></li>
											<li><a href="">Chanel</a></li>
											<li><a href="">Gucci</a></li>
										</ul>
									</div>
								</div>
							</div>
							
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#womens">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											Womens
										</a>
									</h4>
								</div>
								<div id="womens" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="">Fendi</a></li>
											<li><a href="">Guess</a></li>
											<li><a href="">Valentino</a></li>
											<li><a href="">Dior</a></li>
											<li><a href="">Versace</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Kids</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Fashion</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Households</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Interiors</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Clothing</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Bags</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">Shoes</a></h4>
								</div>
							</div>
						</div><!--/category-products-->
					
						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
									<li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
									<li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
									<li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
									<li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
									<li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
									<li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->
						
						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->
						
						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div><!--/shipping-->
					</div>
				</div>
				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">Latest From our Blog</h2>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> Mac Doe</li>
									<li><i class="fa fa-clock-o"></i> 1:33 pm</li>
									<li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
								</ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<img src="{% static 'images/blog/blog-one.jpg' %}" alt="">
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							<a  class="btn btn-primary" href="">Read More</a>
						</div>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> Mac Doe</li>
									<li><i class="fa fa-clock-o"></i> 1:33 pm</li>
									<li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
								</ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<img src="{% static 'images/blog/blog-two.jpg' %}" alt="">
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							<a  class="btn btn-primary" href="">Read More</a>
						</div>
						<div class="single-blog-post">
							<h3>Girls Pink T Shirt arrived in store</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> Mac Doe</li>
									<li><i class="fa fa-clock-o"></i> 1:33 pm</li>
									<li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
								</ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
								<img src="{% static 'images/blog/blog-three.jpg' %}" alt="">
							</a>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							<a  class="btn btn-primary" href="">Read More</a>
						</div>
						<div class="pagination-area">
							<ul class="pagination">
								<li><a href="" class="active">1</a></li>
								<li><a href="">2</a></li>
								<li><a href="">3</a></li>
								<li><a href=""><i class="fa fa-angle-double-right"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
	

templates/product-details.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}

	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for category in category_list %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{ category.category_name }}
										</a>
									</h4>
								</div>
								<div id="sportswear" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="">Nike </a></li>
											<li><a href="">Under Armour </a></li>
											<li><a href="">Adidas </a></li>
											<li><a href="">Puma</a></li>
											<li><a href="">ASICS </a></li>
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}	
						</div><!--/category-products-->
					
						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for brand in brand_list %}
									<li><a href="#"> <span class="pull-right">(50)</span>{{brand.brand_name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->
						
						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->
						
						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div><!--/shipping-->
						
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								<img src="{% static 'images/product-details/1.jpg' %}" alt="" />
								<h3>ZOOM</h3>
							</div>
							<div id="similar-product" class="carousel slide" data-ride="carousel">
								
								  <!-- Wrapper for slides -->
								    <div class="carousel-inner">
										<div class="item active">
										  <a href=""><img src="{% static 'images/product-details/similar1.jpg' %}" alt=""></a>
										  <a href=""><img src="{% static 'images/product-details/similar2.jpg' %}" alt=""></a>
										  <a href=""><img src="{% static 'images/product-details/similar3.jpg' %}" alt=""></a>
										</div>
										<div class="item">
										  <a href=""><img src="{% static 'images/product-details/similar1.jpg' %}" alt=""></a>
										  <a href=""><img src="{% static 'images/product-details/similar2.jpg' %}" alt=""></a>
										  <a href=""><img src="{% static 'images/product-details/similar3.jpg' %}" alt=""></a>
										</div>
										<div class="item">
										  <a href=""><img src="{% static 'images/product-details/similar1.jpg' %}" alt=""></a>
										  <a href=""><img src="{% static 'images/product-details/similar2.jpg' %}" alt=""></a>
										  <a href=""><img src="{% static 'images/product-details/similar3.jpg' %}" alt=""></a>
										</div>
										
									</div>

								  <!-- Controls -->
								  <a class="left item-control" href="#similar-product" data-slide="prev">
									<i class="fa fa-angle-left"></i>
								  </a>
								  <a class="right item-control" href="#similar-product" data-slide="next">
									<i class="fa fa-angle-right"></i>
								  </a>
							</div>

						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<img src="{% static 'images/product-details/new.jpg' %}" class="newarrival" alt="" />
								<input id="product_id" value="{{product_obj.product_id}}" type="hidden" >
								<h2>{{product_obj.product_name}}</h2>
								<p>Web ID: 1089772</p>
								<img src="{% static 'images/product-details/rating.png' %}" alt="" />
								<span>
									<span>US ${{product_obj.product_price}}</span>
									<label>Quantity:</label>
									<input type="text" value="3" />
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
								</span>
								<p><b>Availability:</b> {{product_obj.get_product_availability_display}}</p>
								<p><b>Condition:</b> New</p>
								<p><b>Brand:</b> {{product_obj.product_id.brand_id.brand_name}}</p>
								<a href=""><img src="{% static 'images/product-details/share.png' %}" class="share img-responsive"  alt="" /></a>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->
					
					<div class="category-tab shop-details-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								<li><a href="#details" data-toggle="tab">Details</a></li>
								<li><a href="#companyprofile" data-toggle="tab">Company Profile</a></li>
								<li><a href="#tag" data-toggle="tab">Tag</a></li>
								<li class="active"><a href="#reviews" data-toggle="tab">Reviews {{review_list.count}}</a></li>
							</ul>
						</div>
						<div class="tab-content">
							<div class="tab-pane fade" id="details" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery1.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery2.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery3.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery4.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade" id="companyprofile" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery1.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery3.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery2.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery4.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade" id="tag" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery1.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery2.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery3.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{% static 'images/home/gallery4.jpg' %}" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade active in" id="reviews" >
								<div class="col-sm-12">
									{% for review in review_list %}
									<ul>
										<li><a href=""><i class="fa fa-user"></i>{{review.user_name}}</a></li>
										<li><a href=""><i class="fa fa-clock-o"></i>{{review.created_date.time}}</a></li>
										<li><a href=""><i class="fa fa-calendar-o"></i>{{review.created_date.date}}</a></li>
									</ul>
									<p>{{review.user_review}}</p>
									{% endfor %}
									<p><b>Write Your Review</b></p>
									
									<form id="review_form" type="submit" method="POST">
										{% csrf_token %}
										<span>
											<input type="text" id="name" name="name" required pattern="[a-zA-Z ]+$" placeholder="Your Name"/>
											<input type="email" id="email" name="email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" placeholder="Email Address"/>
										</span>
										<textarea required name="review" id="review" placeholder="Add your reviews"></textarea>
										<b>Rating: </b> <img src="{% static 'images/product-details/rating.png' %}" alt="" />
										<button type="submit" class="btn btn-default pull-right">
											Submit
										</button>
									</form>
									<br>
									<label id="message" style="color: rgb(254, 152, 15);"></label>

								</div>
							</div>
							
						</div>
					</div><!--/category-tab-->

				</div>
			</div>
		</div>
	</section>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'customise_js/product.js' %}"></script>	
{% endblock %}	